spring:
  application:
    name: player
  webflux:
    base-path: /player
  data:
    mongodb:
      host: mongo-player
      port: 27017
      username: root
      password: ${DB_PASSWORD}
      database: admin
      authentication-database: admin

server:
  port: 8020